// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHqKLxqwPEF0AkQ7wQ5hJcWNm4ZGTU7NM',
    appId: '1:473819721520:web:42b18579d59f760f49a2f5',
    messagingSenderId: '473819721520',
    projectId: 'kelpet-8834d',
    authDomain: 'kelpet-8834d.firebaseapp.com',
    storageBucket: 'kelpet-8834d.appspot.com',
    measurementId: 'G-KV7FMS84N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDUpeKLUwVzSj6qO5_XPaxhqD1Pmr9rW8',
    appId: '1:473819721520:android:fc0da7b8b444159849a2f5',
    messagingSenderId: '473819721520',
    projectId: 'kelpet-8834d',
    storageBucket: 'kelpet-8834d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKFRXmJbYIjaJvLgMc0oHwPaD8cJuDLgc',
    appId: '1:473819721520:ios:a43038bf5dd3599f49a2f5',
    messagingSenderId: '473819721520',
    projectId: 'kelpet-8834d',
    storageBucket: 'kelpet-8834d.appspot.com',
    iosBundleId: 'com.example.kelpet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKFRXmJbYIjaJvLgMc0oHwPaD8cJuDLgc',
    appId: '1:473819721520:ios:a43038bf5dd3599f49a2f5',
    messagingSenderId: '473819721520',
    projectId: 'kelpet-8834d',
    storageBucket: 'kelpet-8834d.appspot.com',
    iosBundleId: 'com.example.kelpet',
  );

}